version: 1.4.0-dev-{build}

image:
  - Ubuntu
  - Visual Studio 2019

build: false

# restrict to branches
branches:
  only:
    - master
    - develop

environment:
  # setup tests matrix
  matrix:
    - PYTHON: "3.6"
    - PYTHON: "3.7"
    - PYTHON: "3.8"
    - PYTHON: "3.9"

for:
  - matrix:
      only:
        - image: Ubuntu

    cache:
      # enable cache for Python dependencies
      - "$HOME/.cache/pip"

    init:
      # load virtual env
      - "source $HOME/venv$PYTHON/bin/activate"

      # check current python version
      - "python --version"

    install:
      # install poetry
      - "python -m pip install poetry"

      # install dependencies for test
      - "poetry install --no-ansi"

    test_script:
      # run tests
      - "poetry run pytest -v --cov-report term"

      # run code formatting tests
      - "poetry run black . --check"
      - "poetry run flake8"

    after_test:
      # upload coverage stats to codecov.io
      # codecov token is stored in appveyor settings
      - "poetry run codecov"

  - matrix:
      only:
        - image: Visual Studio 2019

    cache:
      # enable cache for Python dependencies
      - "%LOCALAPPDATA%\\pip\\Cache"

    init:
      # check current python version
      - "py -%PYTHON% --version"

    install:
      # install poetry
      - "py -%PYTHON% -m pip install poetry"

      # install dependencies for test
      - "py -%PYTHON% -m poetry install --no-ansi"

    test_script:
      # run tests
      - "py -%PYTHON% -m poetry run pytest -v --cov-report term"

      # run code formatting tests
      - "py -%PYTHON% -m poetry run black . --check"
      - "py -%PYTHON% -m poetry run flake8"

    after_test:
      # upload coverage stats to codecov.io
      # codecov token is stored in appveyor settings
      - "py -%PYTHON% -m poetry run codecov"
