language: python
python:
  - "3.5"
  - "3.6"

# restrict to branches
branches:
  only:
    - master
    - develop

# command to install python dependencies
install:
  # the features used in setup.cfg require at decent version of setuptools
  - pip install --upgrade "setuptools>=40.0"

  # install dependencies for test
  - pip install -e ".[tests]"

# command to run tests
script:
  # run tests
  - python setup.py test

  # run code formatting tests
  - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then black . --check; fi
  - flake8
