language: python
python:
  - "3.5"
  - "3.6"

# restrict to branches
branches:
  only:
    - master
    - develop

# command to install python dependencies
install:
  - pip install -e "."
  - pip install -e ".[test]"

# command to run tests
script:
  - python setup.py test
  - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then black . --check; fi
  - flake8
