version: 0.0.0-dev-{build}

build: false

# restrict to branches
branches:
  only:
  - develop
  - master

environment:
  # setup special environment variable for Appveyor CI test environment
  # it is used to disable some tests that can be harmful in this context
  APPVEYOR_CI_ENV: 1

  # setup tests matrix
  matrix:
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

# check current python version
init:
  - "py -%PYTHON_VERSION% --version"

# command to install system and python dependencies
install:
  - "py -%PYTHON_VERSION% -m pip install --upgrade \"setuptools>=40.0\""
  - "py -%PYTHON_VERSION% -m pip install -e '.[tests]'"

# command to run tests
test_script:
  - "py -%PYTHON_VERSION% setup.py test"
  - "if NOT %PYTHON_VERSION% == 3.5 (py -%PYTHON_VERSION% -m  black . --check)"
  - "py -%PYTHON_VERSION% -m flake8"
